# config.py

DB_SERVER = "ZYOND\SQLEXPRESS"
DB_NAME = "AppPriceWise1"
DB_USER = "dieu"
DB_PASSWORD = "123"
DB_DRIVER = "ODBC Driver 17 for SQL Server"

SECRET_KEY = "supersecretkey"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
